### ISSUE TITLE
Don't program only on 3.3V 

### ISSUE THREAD

**Issue by vortex314** [EFeru/hoverboard-sideboard-hack-STM#6]
Thanks for your github sources and documentation ! Well done. 

Just tried to program one of the sideboards with an stlink V2, while connecting the 3.3V connection on the SWD pinout. , and was able to remove the protection, but not able to program. Afterwards it became unvisible to the stlink programmer. 
I suspect that the 3.3V goes through the CPU and leaks back to the 5V where there is much more passive load. I'm guessing this leakage current killed the CPU. 
Luckily I have another board and tried with the 5V supply of the STLINK connecting to the RF +5V , this worked fine. 

Maybe adapt the README.MD in that sense ?

 I saw also for the mainboard on other pages, it's not recommended to program just supplying the 3.3V 

Hope this makes sense.

**Comment by vortex314** [comment]
There is some weird thing with these chips, they don't look genuine STM32F103 , when I connect these to the STM32Cubeprogrammer , they only report 32K, I've changed the chip on the board with a 'blue pill' board chip and that works fine. Except that I killed the MPU6050 in the process. :-(

**Comment by EFeru** [comment]
Yes, the sideboard are tricky. In some hoverboards the chip have different memory size.. i have seen some people not able to flash because memory was 32 KB instead of 64kB.

Regarding the supply voltage via the STLink, i didn't have problems. But we can put a warning in Readme, of course.

**Comment by vortex314** [comment]
Thanks for the swift reaction, just got burned by another issue : the wiring on certain boards is not following the convention : black==ground and red==positive voltage. In my case it was just the opposite and saw it proven by an exploding elco on the board. :-D
Luckily I have some spares. But of course it fried the cpu and mpu6050. 
Lesson learned, check and double check before connecting.
